"""price_estimate basis in key

Revision ID: 3cb47c584c0e
Revises: c3e9d521c318
Create Date: 2026-09-14 23:57:07.221894

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cb47c584c0e"
down_revision: str | Sequence[str] | None = "c3e9d521c318"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_price_estimate_scope"), "price_estimate", type_="unique")
    op.create_unique_constraint(
        "uq_price_estimate_scope", "price_estimate", ["issue_id", "grade", "region", "basis"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_price_estimate_scope", "price_estimate", type_="unique")
    op.create_unique_constraint(
        op.f("uq_price_estimate_scope"),
        "price_estimate",
        ["issue_id", "grade", "region"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
