"""coin_issue year

Revision ID: 5c89aedbb616
Revises: d2c1a5bb738c
Create Date: 2026-09-14 20:02:03.951568

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c89aedbb616"
down_revision: str | Sequence[str] | None = "d2c1a5bb738c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coin_issue", sa.Column("year", sa.SmallInteger(), nullable=True))
    # Existing rows (if any) inherit the year of their type before the column becomes required
    op.execute(
        "UPDATE coin_issue SET year = t.year FROM coin_type t WHERE coin_issue.type_id = t.id"
    )
    op.alter_column("coin_issue", "year", nullable=False)
    op.create_check_constraint("ck_coin_issue_year", "coin_issue", "year BETWEEN 1999 AND 2100")
    op.drop_constraint(op.f("uq_coin_issue_variant"), "coin_issue", type_="unique")
    op.create_unique_constraint(
        "uq_coin_issue_variant",
        "coin_issue",
        ["type_id", "year", "mint_mark", "finish", "packaging"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_coin_issue_variant", "coin_issue", type_="unique")
    op.create_unique_constraint(
        op.f("uq_coin_issue_variant"),
        "coin_issue",
        ["type_id", "mint_mark", "finish", "packaging"],
        postgresql_nulls_not_distinct=False,
    )
    op.execute("ALTER TABLE coin_issue DROP CONSTRAINT IF EXISTS ck_coin_issue_year")
    op.drop_column("coin_issue", "year")
    # ### end Alembic commands ###
