"""identification

Revision ID: 852c23eb7fc4
Revises: f4f8a8161de1
Create Date: 2026-09-14 23:12:46.673121

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "852c23eb7fc4"
down_revision: str | Sequence[str] | None = "f4f8a8161de1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("image_path", sa.Text(), nullable=True),
        sa.Column("found_circle", sa.Boolean(), nullable=False),
        sa.Column("top_type_id", sa.UUID(), nullable=True),
        sa.Column("top_score", sa.Float(), nullable=True),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_type_id", sa.UUID(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.ForeignKeyConstraint(["confirmed_type_id"], ["coin_type.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["top_type_id"], ["coin_type.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_identification_created", "identification", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_identification_created", table_name="identification")
    op.drop_table("identification")
    # ### end Alembic commands ###
