"""coin_type mintage_total

Revision ID: d2c1a5bb738c
Revises: 89d65cc6f442
Create Date: 2026-09-14 19:34:29.630855

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2c1a5bb738c"
down_revision: str | Sequence[str] | None = "89d65cc6f442"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coin_type", sa.Column("mintage_total", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coin_type", "mintage_total")
    # ### end Alembic commands ###
