"""image_embedding

Revision ID: d4d4234a5f35
Revises: 852c23eb7fc4
Create Date: 2026-09-14 23:20:15.574517

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4d4234a5f35"
down_revision: str | Sequence[str] | None = "852c23eb7fc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_embedding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("rotation", sa.SmallInteger(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["coin_image.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_id", "rotation", name="uq_image_embedding_rotation"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_embedding")
    # ### end Alembic commands ###
