"""coin_image local_path nullable

Revision ID: e4780859e0af
Revises: 5c89aedbb616
Create Date: 2026-09-14 21:18:39.536066

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4780859e0af"
down_revision: str | Sequence[str] | None = "5c89aedbb616"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("coin_image", "local_path", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("coin_image", "sha256", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("coin_image", "sha256", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("coin_image", "local_path", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
