"""hot path indexes

Revision ID: f4f8a8161de1
Revises: ff66dc5b9170
Create Date: 2026-09-14 22:22:51.420537

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4f8a8161de1"
down_revision: str | Sequence[str] | None = "ff66dc5b9170"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_coin_image_type", "coin_image", ["type_id"], unique=False)
    op.create_index("ix_coin_issue_type", "coin_issue", ["type_id"], unique=False)
    op.create_index(
        "ix_market_observation_auction_queue",
        "market_observation",
        ["observation_kind", "ends_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_observation_auction_queue", table_name="market_observation")
    op.drop_index("ix_coin_issue_type", table_name="coin_issue")
    op.drop_index("ix_coin_image_type", table_name="coin_image")
    # ### end Alembic commands ###
